//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto01.GestaoVendas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Pedidos = new HashSet<Pedido>();
        }
    
        [Required(ErrorMessage ="O documento é obrigatório!")]
        [StringLength(14, MinimumLength =11)]
        public string Documento { get; set; }
        
        [Required(ErrorMessage ="O nome é obrigatório!")]
        public string Nome { get; set; }

        [Required(ErrorMessage ="O telefone é obrigatório!")]
        public string Telefone { get; set; }

        [Required(ErrorMessage ="O e-mail é obrigatório!")]
        [DataType(DataType.EmailAddress, ErrorMessage ="E-mail inválido!")]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedidos { get; set; }
    }
}
